language: generic 

sudo: required

services:
  - docker

before_install:
  - docker build -t isam/react-test -f ./client/Dockerfile.dev ./client
script:
  - docker run -e CI=true isam/react-test npm test

after_success:
  - docker build -t isam/multi-client ./client
  - docker build -t isam/multi-nginx ./nginx
  - docker build -t isam/multi-server ./server
  - docker build -t isam/multi-worker ./worker

  #Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #Take those images and push them to docker hub
  - docker push isam/multi-client
  - docker push isam/multi-nginx
  - docker push isam/multi-server
  - docker push isam/multi-worker