sudo: required
services:
  -docker

before_install:
  - docker build -t isam/react-test -f ./client/Dockerfile.dev ./clent
script:
  - docker run isam/react-test npm test -- --coverage

after_success:
  - docker build isam/multi-client ./cleint
  - docker build isam/multi-nginx ./nginx
  - docker build isam/multi-server ./server
  - docker build isam/multi-worker ./worker